# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .dynamo_table import *
from .lambda_http_app import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "platform",
  "mod": "index",
  "fqn": "pulumi_platform",
  "classes": {
   "platform:index:DynamoTable": "DynamoTable",
   "platform:index:LambdaHttpApp": "LambdaHttpApp"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "platform",
  "token": "pulumi:providers:platform",
  "fqn": "pulumi_platform",
  "class": "Provider"
 }
]
"""
)
